compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

packageExtensions:
  '@octokit/rest@*':
    peerDependencies:
      '@octokit/core': '*'
  graphql-config@*:
    peerDependencies:
      typescript: '*'
  lerna@*:
    peerDependencies:
      '@octokit/core': '*'
  polyfill-library@*:
    peerDependencies:
      '@types/node': '*'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
