nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependencies:
      typescript: "*"
  "@octokit/rest@*":
      peerDependencies:
        "@octokit/core": "*"
  polyfill-library@*:
    peerDependencies:
      "@types/node": "*"
  "@lerna/github-client@*":
    peerDependencies:
      "@octokit/core": "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  "@lerna/version@*":
    peerDependencies:
      "@octokit/core": "*"
  "lerna@*":
    peerDependencies:
      "@octokit/core": "*"
  "@lerna/publish@*":
    peerDependencies:
      "@octokit/core": "*"
