version: '3.7'


services:
  digitransit-ui:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001.tpwd-bb-navi
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: Host:herzberg-elster.bbnavi.de
        traefik.port: '8080'
