version: '3.7'

# This file partially overrides docker-compose.yml, and configures digitransit-ui for deployments.

services:
  digitransit-ui:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/digitransit-ui:bb-angermuende
    environment:
      - FAHRGEMEINSCHAFT_API_KEY=${FAHRGEMEINSCHAFT_API_KEY:?missing env var FAHRGEMEINSCHAFT_API_KEY}
      - API_URL=https://staging.api.bbnavi.de
      - CONFIG=bbnavi-angermuende
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001.tpwd-bb-navi
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        # todo: make instance-specific
        traefik.frontend.rule: Host:staging.bbnavi.de
        # bbnavi:digitransit
        # todo: make instance-specific
        traefik.frontend.auth.basic.users: bbnavi:$$apr1$$s135n0lg$$.yhGUnsFgFVpKW.9UuyTJ/
        traefik.port: '8080'

networks:
  public:
    external: true
