#! /bin/bash

xmllint -o static/assets/svg-sprite.bbnavi-source.svg --format static/assets/svg-sprite.bbnavi-source.svg
xmllint -o static/assets/svg-sprite.bbnavi.svg --format static/assets/svg-sprite.bbnavi.svg
