#! /usr/bin/python3

import xml.dom.minidom


def has_icon(icons, icon_name):
    for i in icons:
        if i.getAttribute("id") == icon_name:
            return True
    return False


hb_source_file = "static/assets/svg-sprite.hb-source.svg"
hsl_source_file = "static/assets/svg-sprite.hsl.svg"
default_source_file = "static/assets/svg-sprite.default.svg"

output_file_name = "static/assets/svg-sprite.hb.svg"

hb_source = xml.dom.minidom.parse(hb_source_file)
hb_icons = hb_source.getElementsByTagName("symbol")

hsl_doc = xml.dom.minidom.parse(hsl_source_file)
hsl_icons = hsl_doc.getElementsByTagName("symbol")

default_doc = xml.dom.minidom.parse(default_source_file)
default_icons = default_doc.getElementsByTagName("symbol")

print(f"Found {len(hb_icons)} icons {hb_source_file}")
print(f"Found {len(hsl_icons)} icons {hsl_source_file}")

output_defs = default_doc.getElementsByTagName("defs")[0]

for icon in hsl_icons:
    icon_id = icon.getAttribute("id")
    if not has_icon(default_icons, icon_id):
        output_defs.appendChild(icon)
        print(f"{icon_id} exists in {hsl_source_file} but not in {default_source_file}. Adding.")

    if not has_icon(hb_icons, icon_id):
        output_defs.appendChild(icon)
        print(f"{icon_id} exists in {hsl_source_file} but not in {hb_source_file}. Adding.")



for icon in hb_icons:
    output_defs.appendChild(icon)

output_file = open(output_file_name, 'w')
output_file.write(default_doc.toprettyxml(indent=" ", newl=""))

print(f"Wrote output to {output_file_name}")
