#! /usr/bin/python3

import xml.dom.minidom


def has_icon(icons, icon_name):
    for i in icons:
        if i.getAttribute("id") == icon_name:
            return True
    return False


hb_source_file = "static/assets/svg-sprite.hb-source.svg"
hsl_source_file = "static/assets/svg-sprite.hsl.svg"
default_source_file = "static/assets/svg-sprite.default.svg"

output_file_name = "static/assets/svg-sprite.hb.svg"

hb_source = xml.dom.minidom.parse(hb_source_file)
hb_icons = hb_source.getElementsByTagName("symbol")

hsl_doc = xml.dom.minidom.parse(hsl_source_file)
hsl_icons = hsl_doc.getElementsByTagName("symbol")

default_doc = xml.dom.minidom.parse(default_source_file)
default_icons = default_doc.getElementsByTagName("symbol")

print(f"Found {len(hb_icons)} icons {hb_source_file}")
print(f"Found {len(hsl_icons)} icons {hsl_source_file}")

output_defs = hb_source.getElementsByTagName("defs")[0]
print("")
print(f"Icons that exist in {hb_source_file}")
print("")

symbols = {}
for icon in hb_icons:
    icon_id = icon.getAttribute("id")
    symbols[icon_id] = icon
    print(icon_id)

for icon in hb_icons:
    icon_id = icon.getAttribute("id")
    for child in icon.childNodes:
        if child.nodeName == 'use':
            ref = child.getAttribute("xlink:href")[1:]
            symbol = symbols[ref].cloneNode(True)
            g = hb_source.createElement("g")
            g.setAttribute("style", child.getAttribute("style"))
            for symbolChild in symbol.childNodes:
                print(symbolChild.nodeName)
                g.appendChild(symbolChild.cloneNode(True))
            icon.replaceChild(g, child)
            icon.setAttribute("viewBox", symbol.getAttribute("viewBox"))
            print("Inlined use for {} by {}".format(icon_id, ref))

print("")
print(f"Icons added from {default_source_file}")
print("")

for icon in default_icons:
    icon_id = icon.getAttribute("id")

    if not has_icon(hb_icons, icon_id):
        output_defs.appendChild(icon)
        print(icon_id)

print("")
print(f"Icons added from {hsl_source_file}")
print("")

for icon in hsl_icons:
    icon_id = icon.getAttribute("id")

    if not has_icon(default_icons, icon_id) and not has_icon(hb_icons, icon_id):
        output_defs.appendChild(icon)
        print(icon_id)


output_file = open(output_file_name, 'w')
output_file.write(hb_source.toprettyxml(indent=" ", newl=""))

print("")
print(f"Wrote output to {output_file_name}")
