#!/usr/bin/env python3
import os, sys
import json

# Update the caresteouvert repo.
if not os.path.isdir('caresteouvert'):
    os.system('git clone git@github.com:osmontrouge/caresteouvert.git')
else:
    os.chdir('caresteouvert')
    os.system('git pull')
    os.chdir('..')

# Get the categories with existing German translations - remote
f = open('caresteouvert/locales/de.json',)
data = json.load(f)

remote_trans = []
for line in data['categories']:
    word = line.split(": ")[0].strip("\"")
    remote_trans.append(word)

f.close()

# Get the categories with existing German translations - local
local_trans = []
keep = False
with open('app/translations.js') as f:
    for line in f:
        if line.__contains__("de: {"):
            keep = True
        if keep and line.__contains__("poi-"):
            word = line.split("': ")[0].split("-")[1]
            local_trans.append(word)
        if line.__contains__("},"):
            keep = False

# Find the categories we do not have translations locally
new_trans = list(set(remote_trans) - set(local_trans))
print(new_trans)