name: Process hotfix push
on:
  push:
    branches:
      - hotfix
jobs:
  docker-push:
    if: github.ref == 'refs/heads/hotfix'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set time zone to Europe/Helsinki
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"
      - name: Build docker image from next and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          DOCKER_BASE_TAG: hotfix
