name: Process hotfix push
on:
  push:
    branches:
      - hotfix
jobs:
  docker-push:
    if: github.ref == 'refs/heads/hotfix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set time zone to Europe/Helsinki
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"

      - name: configure Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}

      - name: Cache .yarn/cache
        uses: actions/cache@v3
        with:
          path: '.yarn/cache'
          key: yarn-cache-${{ github.ref_name }}
          restore-keys: yarn-cache-v2

      - name: determine Docker image tags
        id: docker-tags
        run: |
          echo "::set-output name=permanent-tag::hotfix-$(date +"%Y-%m-%dT%H.%M.%S")-${GITHUB_SHA:0:7}"
      - name: build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            hsldevcom/digitransit-ui:hotfix
            hsldevcom/digitransit-ui:${{ steps.docker-tags.outputs.permanent-tag }}
          push: true
